# Generated by Django 5.0.6 on 2024-06-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('bod', models.DateField()),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=39)),
            ],
        ),
    ]
